#!/usr/bin/env bash
if [[ $1 == "yes" ]]; then
    {
        echo 'this is testing EOF with indent'
        echo 'this is testing EOF with indent'
        cat -
        echo 'these lines wanted to be without leading indent'
        echo 'these lines wanted to be without leading indent'
    } > ./eofoutput.txt
fi
